# Generated by Django 4.2 on 2025-02-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified_email',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
